apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-chart.fullname" . }}-db
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
data:
    db.config: |
    # DB
    {{- if .Values.database.config }}
    {{- .Values.database.config | nindent 6 }}
    {{- end -}}
    {{- if not .Values.database.config }}
      host=localhost
      database=test
    {{- end }}