{{- if .Values.database }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-chart.fullname" . }}-db-secret
type: Opaque
data:
  username: {{ .Values.database.username }}
  password: {{ .Values.database.password }}
{{- end -}}