{{- if .Values.kafka.consumer.ccloud }}
{{- if (not .Values.kafka.consumer.ccloud.fromExistingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-chart.fullname" . }}-kafka-secret
type: Opaque
data:
  clusterApiKey: {{ .Values.kafka.consumer.ccloud.key }}
  clusterApiSecret: {{ .Values.kafka.consumer.ccloud.secret }}
{{- end -}}
{{- end -}}

